# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
    -   id: trailing-whitespace
        exclude_types: [markdown]
    -   id: end-of-file-fixer
        exclude_types: [markdown]
    -   id: check-yaml
    -   id: check-added-large-files
        args: ["--maxkb=80000"]
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.5.2
    hooks:
    - id: isort
      types: [python]
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 0.4.1
    hooks:
    -   id: nbqa-black
        additional_dependencies: [black==20.8b1]
        args: [--nbqa-mutate]
    -   id: nbqa-pyupgrade
        additional_dependencies: [pyupgrade==2.7.3]
        args: [--nbqa-mutate]
    -   id: nbqa-isort
        additional_dependencies: [isort==5.6.4]
        args: [--nbqa-mutate]
-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.25.0
    hooks:
    -   id: markdownlint
        args: [--fix]
